create table if not exists singelo_catalogo_instagram (
    id bigint generated by default as identity primary key,
    instagram_id text unique,
    username text not null,
    title text not null,
    category text not null default 'Outros',
    description text not null default '',
    price numeric(10,2),
    image_url text,
    image_urls jsonb not null default '[]'::jsonb,
    permalink text,
    active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);